const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  isElectron: true,
  openDirectoryDialog: (defaultPath) => ipcRenderer.invoke('dialog:openDirectory', defaultPath),
  openFileDialog: (defaultPath) => ipcRenderer.invoke('dialog:openFile', defaultPath),
  showItemInFolder: (fullPath) => ipcRenderer.invoke('shell:showItemInFolder', fullPath),
  openPath: (fullPath) => ipcRenderer.invoke('shell:openPath', fullPath),
  getDesktopSources: () => ipcRenderer.invoke('desktopCapturer:getSources'),
  fs: {
    selectFolder: () => ipcRenderer.invoke('fs:selectFolder'),
    readDirectoryChildren: (dirRelOrFullPath) => ipcRenderer.invoke('fs:readDirectoryChildren', dirRelOrFullPath),
    readDirectoryTree: (dirPath) => ipcRenderer.invoke('fs:readDirectoryTree', dirPath),
    readFileDetails: (filePath, options) => ipcRenderer.invoke('fs:readFileDetails', filePath, options),
    writeFile: (filePath, content) => ipcRenderer.invoke('fs:writeFile', filePath, content),
    createFile: (filePath, content) => ipcRenderer.invoke('fs:createFile', filePath, content),
    createDirectory: (dirPath) => ipcRenderer.invoke('fs:createDirectory', dirPath),
    deleteItem: (targetPath) => ipcRenderer.invoke('fs:deleteItem', targetPath),
    renameItem: (oldPath, newPath) => ipcRenderer.invoke('fs:renameItem', oldPath, newPath),
    moveItem: (srcPath, destPath) => ipcRenderer.invoke('fs:moveItem', srcPath, destPath),
    searchCodebase: (options) => ipcRenderer.invoke('fs:searchCodebase', options),
  },
  git: {
    getStatus: (targetRoot) => ipcRenderer.invoke('git:status', targetRoot),
    getDiff: (options) => ipcRenderer.invoke('git:diff', options),
    stage: (options) => ipcRenderer.invoke('git:stage', options),
    unstage: (options) => ipcRenderer.invoke('git:unstage', options),
    discard: (options) => ipcRenderer.invoke('git:discard', options),
    commit: (options) => ipcRenderer.invoke('git:commit', options),
    push: (options) => ipcRenderer.invoke('git:push', options),
    pull: (options) => ipcRenderer.invoke('git:pull', options),
    fetch: (targetRoot) => ipcRenderer.invoke('git:fetch', targetRoot),
    init: (options) => ipcRenderer.invoke('git:init', options),
    getBranches: (targetRoot) => ipcRenderer.invoke('git:branches', targetRoot),
    checkout: (options) => ipcRenderer.invoke('git:checkout', options),
    getRemotes: (targetRoot) => ipcRenderer.invoke('git:remotes', targetRoot),
    addRemote: (options) => ipcRenderer.invoke('git:addRemote', options),
    getLog: (options) => ipcRenderer.invoke('git:log', options),
    clone: (options) => ipcRenderer.invoke('git:clone', options),
  }
});
